# Generated by Django 4.2.5 on 2023-09-05 14:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='baslik', unique=True),
        ),
    ]
