# Generated by Django 4.2.5 on 2023-09-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='mesaj',
        ),
    ]
