# Generated by Django 4.2.5 on 2023-09-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='news_images/'),
        ),
    ]
