# Generated by Django 4.2.5 on 2023-09-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_author_alter_news_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Yazar', 'verbose_name_plural': 'Yazar'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=120)),
                ('Comment', models.TextField()),
                ('News', models.ForeignKey(default='yorum', on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name': 'Yorumlar',
                'verbose_name_plural': 'Yorumlar',
                'db_table': 'Comments',
            },
        ),
    ]
