# Generated by Django 4.2.5 on 2023-09-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_author_options_alter_author_table_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='News',
            new_name='news',
        ),
    ]
